### ISSUE TITLE
Evaluate whether we need more unit tests.

### ISSUE THREAD

**Issue by MikeHopcroft** [BitFunnel/BitFunnel#24]
The following Utilities classes are missing unit tests as of d3fc1861:

- ConsoleLogger
- LockGuard
- Logging
- LogLevel
- MurmurHash2
- Mutex
- NullLogger
- Stopwatch
- ThreadManager (tested indirectly by TaskDistributor)
- ThreadsafeCounter (tested indirectly by TaskDistributor)

**Comment by danluu** [comment]
I believe we talked about this a couple months ago and decided that, for now, we're going to go with more integration tests instead of adding unit tests to everything.

Additionally, a lot of the most obvious candidates for testing in the list here have been replaced by standard library implementations.
