### ISSUE TITLE
DocumentFrequencyTable contains bogus quotes?

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#304]
~~~
bf41e70fccfa9d68,1,1,6.59631e-05,"י""חל"
...
ce650c2fe8803b94,1,1,6.59631e-05,"ם""במר"
...
91480dda51fba8d7,1,1,6.59631e-05,"ת""מא"
...
~~~

These all come from terms where the language is right-to-left instead of left-to-right. This specific thing prevents us from creating a comprehensive query log by taking the text of all terms and feeding them back into BitFunnel (after stripping out enclosing quotes) because the internal quotes confuse the BitFunnel parser. We could strip out the internal quotes, but if the DocumentFrequencyTable output is correct, we're actually considering those to be part of the term? If so, we have terms that are unquery-able.

I'm filing this on BitFunnel even though there's a decent chance this is a `Workbench` issue because I don't know "whose" bug this is yet.

**Comment by danluu** [comment]
It looks like, for the first one of these, `DocumentFrequencyTable::Write` is getting a (probably mangled) value that has a single escaped quote in it.

> "לח\"י"

![image](https://cloud.githubusercontent.com/assets/157136/20291660/9c3214ca-aa9c-11e6-9380-dc1672ab06f7.png)

`CsvTsv` appears to be mangling it further and somehow producing a second quote character.

**Comment by MikeHopcroft** [comment]
The quote from CsvTsv is not additional mangling - this is correct behavior. CsvTsv implements http://tools.ietf.org/html/rfc4180. The double quote is used to escape fields with commas in them, and therefore, the quote is also used to escape the quote. If you are seeing a second quote, it may be because the application is treating the file as plain text, instead of csv. If this is the case, the additional quote can be addressed by using the CsvTsv parser.

**Comment by MikeHopcroft** [comment]
Now that CsvExtract has the -plaintext option, we should see if this issue should be closed. CsvExtract with -plaintext will remove any extra quotes added for csv escaping of strings that contain quote characters. There is still the question of why terms have quotes in the first place. This may be a workbench issue.

**Comment by hausdorff** [comment]
If I understand both these issues correctly, this issue is very probably related to #312. In that issue the basic problem is that we occasionally have numbers as terms, like `1,000,000`. The CSV "spec" (if you can call it that) needs a way to specify that an element itself has comments, and so the usual way of escaping it is to wrap the term in quotes, like `"1,000,000". This, of course, causes our parser confusion.

Unless I'm missing something, the `-plaintext` flag will actually make this issue worse, since it will truncate all terms that themselves contain commas. So for example if you have a row like `"1,000,000",cow`, then `CsvExtract` will map this -> `1,000,000,cow`. It seems to me that this is not what we want.

If that's correct, then it seems like a better solution would be to:
* Fix up the CsvTsv parser to deserialize escaped and quoted CSV elements correctly, _i.e._, cause it to take a quoted element like `"1,000,000"` and deserialize this to a the string `1,000,000`, without the quotes.
* Remove the `-plaintext` flag.

Thoughts?

**Comment by MikeHopcroft** [comment]
The CsvTsv parser implements the "spec" at http://tools.ietf.org/html/rfc4180 and to the best of my knowledge (and according to the unit tests) handles escaping correctly. The BitFunnel query parser does not read csv-encoded data - it reads plain text. We added the -plaintext flag to the column extractor tool to allow us to get a file of queries that are not csv-encoded so that these queries can be parsed correctly without having to worry about quotes added by csv escaping.

Issue 304 describes a problem that seems to originate from WikiExtractor or Workbench producing terms with double quotes in them. We need to understand if these are legitimate terms or if the quotes are due to some utf-8, bidirectional bug.

Issue 312 describes a problem where it appears that numbers with commas in them are passed through WikiExtractor and Workbench. While these commas are not problematic, it seems that Lucene's analyzer should be addressing them. It is possible that the term "1,234" should be encoded verbatim, but it is also possible that Lucene would treat this as "1234" or as "1" and "234". We should get to the bottom of this as it might be evidence that we are not processing the corpus correctly.

**Comment by hausdorff** [comment]
Let me clarify the specific things I said to address your questions here.

Regarding #312, when we did the last pass on Workbench's [issue 5](https://github.com/BitFunnel/Workbench/issues/5), we did a fairly detailed investigation about what punctuation was and was not emitted (and filtered) by the Lucene tokenizer. You may remember my explanation to you that commas are filtered in some context (such as when the comma trails a term, but is followed by whitespace, as in the string `"cow, "`), but preserved in other contexts, such as numbers (such as the example I gave above, the string `"1,000,000"`). I am happy to investigate other suspicious terms, but based on what I have seen so far in these issues, my belief is that this is working as expected.

Regarding the present issue #304, how are are you that this is really coming from Workbench? The Lucene tokenizer does remove double quotes (more strictly, in fact, than it does commas: regardless of the place in the token, the double quote is removed), and I have looked at the issue, and confirmed that we're emitting the term `1,000` as a string without quotes, and that we're later writing it down in `DocFreqTable-0.csv` as a quoted string `"1,000"`. I'm not saying there's not a bi-directional encoding bug here, but based on this analysis I think it is reasonable to conclude that at least some manifestations of this bug are caused by our CSV utilities. My belief is that the document frequency table is (correctly) emitting CSV elements with commas in them. For example, since (as I mention above) the Lucene tokenizer considers `"1,000,000"` a valid term, it will happily emit it with commas intact. Since we are then passing this to BitFunnel, the document frequency tables are correctly emitting this as a quoted string.

Do you still disagree? Please let me know what I can clarify.

If we do agree, then my conclusions are the following:
* If the Lucene tokenizer is emitting strings with commas in them `"1,000,000"`, then the `CsvExtract` flag `-plaintext` is probably doing something dangerous by mapping `"1,000,000"` -> `1,000,000`, as this will mangle the rest of the CSV. In the case where you're just selecting the first column of the document histogram and simply using the single-column result as a query log, this will probably work fine. But if you're projecting some CSV file to another CSV file, then you'll end up with malformatted CSV, since the spec does have opinions about each row having the same number of columns.

The fix for this could be either of the following:
* We can cause Workbench to filter all commas, which will make `CsvExtract`'s `-plaintext` flag safe in our context (though, I argue, semantically misleading). This should be followed by re-generating the corpus.
* We can retire the `-plaintext` flag, and perhaps cause the query command to strip out extraneous quotes.

**Comment by hausdorff** [comment]
I'm not sure how people feel about what I've said above, but if my explanation above sounds plausible, then I'm happy to implement one of the proposed solutions myself.

**Comment by hausdorff** [comment]
After I published the previous response, I did kick off a batch job to look in our corpus for other discrepancies to try to make sure there really isn't a UTF decode bug. At this point, I think we can be pretty confident there is no UTF decode bug here, so let me address @danluu's issue directly and then state my recommendations.

To Dan's issue. It turns out that in Hebrew, the `"` character is [Gershayim](https://en.wikipedia.org/wiki/Gershayim), a typographical mark that is important to the meaning of the word that contains it. The Lucene `StandardTokenizer` does not consider this to be strippable punctuation, so it is preserved in these tokens. So, when I said that quote-stripping is even more strict than comma-stripping in Lucene, I could have been a bit more precise: there is at least one exception in which double quote marks are not stripped out (_i.e._, when it seems to be Gershayim).

My recommendations. I think I am comfortable saying now that I'm pretty sure my recommendations from before still apply.

Curious to hear your thoughts on this.

**Comment by MikeHopcroft** [comment]
We're co-mingling issues here. This bug is about the double quote character appearing within Hebrew terms. It seems that wikiextractor and Workbench and Lucene are handling this case correctly, so the problem is that we are constructing invalid query logs because, in the BitFunnel query language, an un-escaped double quote indicates the start of a phrase.

The fix is to create a static QueryParser::Escape() method that will take an un-escaped string and convert it to an escaped string suitable for use by QueryParser. Then when we prepare query logs mechanically (where there is an opportunity to include terms that properly contain double quotes or other reserved characters), we should use this method to escape each term.

I have updated issue 312 to explain the actual problem with commas in search terms. Alex raised a potential the csv encoding issue relating to commas in this thread. I will attempt to clarify that aspect here.

The file format for the DocumentFrequencyTable is csv, so term fields in this file will be csv escaped if they contain certain characters like comma and double quote. This is the correct behavior for DocumentFrequencyTable.

When we prepare a query log from the DocumentFrequencyTable, we must parse the file using the CsvTsv library to remove any csv escaping. We will then have plain text values for terms, which may contain commas or double quotes or whitespace.

If the terms only contain commas we may include them directly in a query because the comma has no special meaning to the BitFunnel query parser. If the terms contain whitespace, double quotes, or other characters reserved by the BitFunnel query parser, they must be escaped using the aforementioned QueryParser::Escape() method.

The -plaintext option on the CsvExtract utility is dangerous if your intention is to product a csv file. If your intention is to produce a plaintext file the option works fine. In the case of generating a query log by  extracting the term column from the DocumentFrequencyTable, the -plaintext option is appropriate and works correctly. The problem is that the the input to the query parser is not strictly plaintext - BitFunnel requires that certain characters be escaped.

We may want to add an -escape option to the tool or create a dedicated query log generator.

**Comment by MikeHopcroft** [comment]
95221dfdd93c96bbacaf4fa2f0c0ad32bd30d7d2 implements escaping in the Query Parser and CsvExtract. Dan: can we close this issue now?

**Comment by danluu** [comment]
Yeah, we can now run the ingestion/query flow without either crashing or having an external step that changes the escapes.
