### ISSUE TITLE
Order of magnitude slowdown caused by recent changes

### ISSUE THREAD

**Issue by danluu** [BitFunnel/BitFunnel#324]
Between the fixes to the dedupe buffer and the fixes to the fixes I'm observing a roughly one order of magnitude slowdown.

Running the usual `chunked1` corpus with the DocumentFrequencyTable, I get the following result:

~~~
238: load chunk /tmp/wikipedia//AC/wiki_35
239: query log /tmp/terms.txt
Processing queries from log at "/tmp/terms.txt"
Writing results ...
Results:
Print
Thread count: 4
Unique queries: 455198
Queries processed: 455198
Elapsed time: 63.4285
QPS: 7176.55
240: quit
~~~

If I had to guess, I would guess that we have a bug in how we handle higher rank TermTreatments and that we're doing 8x more work than necessary with our rank3 TermTreatment.

**Comment by danluu** [comment]
Whatever's going on here, it doesn't appear to affect the speed of the compiled code (as much?)

~~~
239: query log /tmp/terms.txt
Processing queries from log at "/tmp/terms.txt"
Writing results ...
Results:
Print
Thread count: 4
Unique queries: 455198
Queries processed: 455198
Elapsed time: 9.39571
QPS: 48447.4
240: quit
~~~

That result is slower than I'm used to seeing from compiled code, but I wonder if that's just a result of having slices that are roughly half full.

**Comment by MikeHopcroft** [comment]
I saw this as well, but wasn't able to pin down the cause last night. I think we should investigate before committing. My leading theory is that our slices have a capacity of 32k (see the repo status command) and we're only loading 15k documents. Therefore we're scanning 50% for no value.

Sent from my Windows Phone
________________________________

**Comment by MikeHopcroft** [comment]
You might try changing the 512 multiplier in SimpleIndex to something like 256 to make the slice capacity tightly fit the document count. Just be sure you don't go too tight and end up with one full slice and another almost empty one.

Sent from my Windows Phone
________________________________
From: Mike Hopcroft<mailto:mhop@microsoft.com>
Sent: ‎11/‎30/‎2016 8:51 AM
To: BitFunnel/BitFunnel<mailto:reply@reply.github.com>
Subject: RE: [BitFunnel/BitFunnel] Order of magnitude slowdown caused by recent changes (#324)

I saw this as well, but wasn't able to pin down the cause last night. I think we should investigate before committing. My leading theory is that our slices have a capacity of 32k (see the repo status command) and we're only loading 15k documents. Therefore we're scanning 50% for no value.

Sent from my Windows Phone
________________________________

**Comment by danluu** [comment]
I tried the 512->256 change, and there's a slight speedup, which is what I'd expect.

If I look QueryPipelineStatistics for interpreted mode, it's pretty clear reading wayyy too much:

~~~
query,rows,matches,quadwords,cachelines,parse,plan,match
from,2,12810,4333,542,0.000119305,3.6731e-05,0.0184971
which,2,12402,4333,542,0.041567,1.5111e-05,0.0450332
also,2,12275,4333,542,0.0415312,1.4876e-05,0.0444905
one,2,11548,4333,542,0.0270582,9.815e-06,0.0395058
other,2,11442,4333,542,4.9058e-05,1.9564e-05,0.000611662
have,2,11420,4333,542,4.4331e-05,4.765e-06,0.000593331
has,2,11297,4333,542,4.1105e-05,3.97e-06,0.000566743
~~~

We used to read 477 qwords for private rows and we're now reading 4333 qwords (9x as much).

**Comment by danluu** [comment]
In this configuration (Rank3Rank0, 256* minimum slice size), we have a `SliceCapacity` of `262144` and we have `15160` documents. It's actually surprising that the NativeCode version executes so quickly --  maybe it only hits the `DocumentActive` row and we can do that very quickly?

Anyway, I think the issue is that `GetMinimumBlockSize` is dependent on rank. We're multiplying it by a large number so that we don't get blocks that are way too small at low ranks, but that creates what are pretty large slices (for our minimal test corpuses) at higher ranks.

I think the longer term solution is that this needs to be configurable, because the optimal number is going to depend on the corpus size. For now, I'm going to get introduce a method called `GetReasonableBlockSize` or something that tries to create decent block size that works with the test corpuses we're using.
