### ISSUE TITLE
REPL "show rows" command does not list all documents/columns

### ISSUE THREAD

**Issue by jondgoodwin** [BitFunnel/BitFunnel#408]
For example, when ingesting the WIkipedia corpus (cache chunk chunks/AA/wiki_00), REPL "show rows anarchy" only lists two of the 41 documents in that chunk as columns. They are always the same two documents regardless of what term is given.

**Comment by jondgoodwin** [comment]
Evidently, this is intentional (if cryptic) behavior.

"show rows" accepts two parameters: a term and shard number. Shard number is optional and assumed to be 0, if not specified. Thus, "show rows anarchy" only shows the documents placed in shard 0. "show rows anarchy 1" shows the documents placed in shard 1.

Presumably, the ["Sample Data" blog's screens](http://bitfunnel.org/sample-data/) were captured back when all documents were placed in the same shard. Now that sharding is in play, the results are different.

* Should we change the "show rows" logic so that if no shard is explicitly specified, it shows documents from all shards?
* Should we add outputted help text which mentions the existence of the optional shard parameter on "show rows"?

**Comment by MikeHopcroft** [comment]
Let's discuss this one on the call. It is complicated because the command can only show a small number of columns at a time. We need to decide which scenario we're targeting for `show rows`. Originally it was added for debugging purposes where examining the first few documents in the first shard was sufficient.

An option to consider is to add another command called `shard x` which would set the default shard to use for queries and `show rows`. Perhaps `shard` with no parameters would clear the default shard so that all shards are used.

**Comment by jondgoodwin** [comment]
This issue is addressed by https://github.com/BitFunnel/BitFunnel/pull/420.
